### ISSUE TITLE
3.2 Creación del paquete repositorio y la Interface -> EstudianteRepositorio = Parte 1, 2 y 3

### ISSUE THREAD

**Issue by SergioMezzabotta** [CodeSystem2022/BugArmy-Cuarto-Semestre#15]
Parte 1: https://drive.google.com/file/d/1rCjAD4sA6ruNVN-_gKB7xY4lwPhTnDyP/view
Parte 2: https://drive.google.com/file/d/16DQrVvmr6eiJe06_LZZEKudLNHtJUArU/view
Parte 3: https://drive.google.com/file/d/1vUaoWoTZ5u-_gSD3B25yf1T2SdjPK2tg/view

**Comment by chimydevs** [comment]
Eso que nos pasaste al Ivo y a mi es lo de la semana que viene, (abrió el 30) ahí subí lo de la semana 2, que fue lo que abrió apenas cerró la semana 1 (el 23) la semana se abre el miércoles, que es el ultimo dia que tenemos con el profe, ahi deja lo que hay que hacer durante la semana, lo de la clase 3 seria del 30 (ayer) al  6 de la semana que viene. 
anashei
